// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbcysuwzhxdmcdwvvuvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iY3lzdXd6aHhkbWNkd3Z2dXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MjE0OTAsImV4cCI6MjA1ODA5NzQ5MH0.GRB_38790QCy2wiMpqSM86kExdFMJt2quNDJEshadlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);